- name: get cfssl
  get_url: 
    url: https://pkg.cfssl.org/R1.2/cfssl_linux-amd64
    dest: /usr/local/bin/cfssl
    mode: 744
  tags: cert

- name: get cfssljson
  get_url:
    url: https://pkg.cfssl.org/R1.2/cfssljson_linux-amd64
    dest: /usr/local/bin/cfssljson
    mode: 744
  tags: cert

- name: get cfssl-certinfo
  get_url:
    url: https://pkg.cfssl.org/R1.2/cfssl-certinfo_linux-amd64
    dest: /usr/local/bin/cfssl-certinfo
    mode: 744
  tags: cert

- name: create work space
  file: 
    path: /tmp/tls
    state: directory
  tags: cert

- name: copy file to work space
  copy:
    src: "{{ item }}"
    dest: /tmp/tls/{{ item }}
  with_items:
  - ca-config.json
  - ca-csr.json
  - admin-csr.json
  - kube-proxy-csr.json
  - metrics-server-csr.json
  tags: cert

- name: copy template to work space
  template:
    src: server-csr.j2
    dest: /tmp/tls/server-csr.json
  tags: cert

- name: gen cert 
  shell:
    chdir: /tmp/tls
    cmd: 
      cfssl gencert -initca ca-csr.json | cfssljson -bare ca -;
      cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes server-csr.json | cfssljson -bare server;
      cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes admin-csr.json | cfssljson -bare admin;
      cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes kube-proxy-csr.json | cfssljson -bare kube-proxy;
      cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -profile=kubernetes metrics-server-csr.json | cfssljson -bare metrics-server;
  tags: cert


    

