- name: down kubectl
  get_url:
    url: https://jusene.gitee.io/tools/kubernetes/1.18.2/packages/amd64/kubectl
    dest: /usr/local/bin/kubectl
  delegate_to: 127.0.0.1
  when: ansible_architecture == "x86_64"
  tags: master

- name: down kubectl
  get_url:
    url: https://jusene.gitee.io/tools/kubernetes/1.18.2/packages/arm64/kubectl
    dest: /usr/local/bin/kubectl
  delegate_to: localhost
  when: ansible_architecture == "aarch64"
  tags: master

- name: create kubeconfig directory
  file:
    path: /tmp/kubeconfig
    state: directory
  delegate_to: 127.0.0.1
  tags: master

  
- name: create bootstrap kubeconfig
  shell:
    cmd:
      kubectl config set-cluster kubernetes --certificate-authority=/etc/kubernetes/ssl/ca.pem --embed-certs=true --server=https://{{ MASTER_VIP }}:8443 --kubeconfig=/tmp/kubeconfig/bootstrap.kubeconfig;
      kubectl config set-credentials kubelet-bootstrap --token={{ BOOTSTRAP_TOKEN }} --kubeconfig=/tmp/kubeconfig/bootstrap.kubeconfig;
      kubectl config set-context default --cluster=kubernetes --user=kubelet-bootstrap --kubeconfig=/tmp/kubeconfig/bootstrap.kubeconfig;
      kubectl config use-context default --kubeconfig=/tmp/kubeconfig/bootstrap.kubeconfig;
  delegate_to: localhost
  tags: master

- name: create kube-proxy kubeconfig
  shell:
    cmd:
      kubectl config set-cluster kubernetes --certificate-authority=/tmp/tls/ca.pem --embed-certs=true --server=https://{{ MASTER_VIP }}:8443 --kubeconfig=/tmp/kubeconfig/kube-proxy.kubeconfig;
      kubectl config set-credentials kube-proxy --client-certificate=/tmp/tls/kube-proxy.pem --client-key=/tmp/tls/kube-proxy-key.pem --embed-certs=true --kubeconfig=/tmp/kubeconfig/kube-proxy.kubeconfig;
      kubectl config set-context default --cluster=kubernetes --user=kube-proxy --kubeconfig=/tmp/kubeconfig/kube-proxy.kubeconfig; 
      kubectl config use-context default --kubeconfig=/tmp/kubeconfig/kube-proxy.kubeconfig;
  delegate_to: localhost
  tags: master

