- name: down bindary file
  #get_url:
  #  url: "https://jusene.gitee.io/tools/kubernetes/1.18.2/packages/amd64/{{ item }}"
  #  dest: "/usr/local/bin/{{ item }}"
  #  mode: 744
  shell:
    cmd:
  #    wget https://jusene.gitee.io/tools/kubernetes/1.18.2/packages/amd64/{{ item }} -O /usr/local/bin/{{ item }};
      chmod +x /usr/local/bin/kube*
  when: ansible_architecture == "x86_64"
  tags: master
  with_items:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - kubectl


- name: down bindary file
  #get_url:
  #  url: "https://jusene.gitee.io/tools/kubernetes/1.18.2/packages/arm64/{{ item }}"
  #  dest: "/usr/local/bin/{{ item }}"
  #  mode: 744
  shell:
    cmd:
      wget https://jusene.gitee.io/tools/kubernetes/1.18.2/packages/arm64/{{ item }} -O /usr/local/bin/{{ item }};
      chmod +x /usr/local/bin/kube*
  when: ansible_architecture == "aarch64"
  tags: master
  with_items:
  - kube-apiserver
  - kube-controller-manager
  - kube-scheduler
  - kubectl

- name: create log directory
  file:
    path: /var/log/kubernetes
    state: directory
  tags: master

- name: create audit.log
  file:
    path: /var/log/kubernetes/k8s-audit.log
    state: touch
  tags: master

- name: copy token csv
  template:
    src: token.j2
    dest: /etc/kubernetes/token.csv
  tags: master

- name: copy cert file
  copy:
    src: "/tmp/tls/{{item}}"
    dest: "/etc/kubernetes/ssl/{{item}}"
  with_items:
  - ca-key.pem
  - ca.pem
  - server-key.pem
  - server.pem
  - metrics-server-key.pem
  - metrics-server.pem
  tags: master

- include: apiserver.yaml
- include: controller.yaml
- include: scheduler.yaml
- include: admin.yaml
- include: kubeconfig.yaml
